font:
  normal:
    family: "Roboto Mono"
    style: Regular
  bold:
    family: "Roboto Mono"
    style: Bold
  size: 13.0

# Solaraized Dark theme
colors:
  primary:
    background: '#002b36' # base03
    foreground: '#ffffff' # base0
    # foreground: '#839496' # base0
  cursor:
    text:   '#002b36' # base03
    cursor: '#839496' # base0
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3

# Monokai theme
# colors:
#   primary:
#     background: '#1B1D1E'
#     foreground: '#F8F8F2'
#   normal:
#     black:   '#333333'
#     red:     '#C4265E'
#     green:   '#86B42B'
#     yellow:  '#B3B42B'
#     blue:    '#6A7EC8'
#     magenta: '#8C6BC8'
#     cyan:    '#56ADBC'
#     white:   '#E3E3DD'
#   bright:
#     black:   '#666666'
#     red:     '#F92672'
#     green:   '#A6E22E'
#     yellow:  '#E2E22E'
#     blue:    '#819AFF'
#     magenta: '#AE81FF'
#     cyan:    '#66D9EF'
#     white:   '#F8F8F2'
