## Autostart
exec-once = sleep 5; waybar
exec-once = hyprpaper
## clipboard cliphist
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
## notifications
exec-once = mako
## hyprpolkit
exec-once = systemctl --user start hyprpolkitagent
## kwallet
# exec-once=/usr/lib/pam_kwallet_init
## gnome-keyring
exec-once = gnome-keyring
