## Autostart

## waybar (barra superior)
exec-once = sleep 5; waybar

## wallpaper
exec-once = hyprpaper

## clipboard cliphist
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

## notifications
exec-once = mako

## hyprpolkit
exec-once = systemctl --user start hyprpolkitagent

## kwallet
# exec-once=/usr/lib/pam_kwallet_init

## gnome-keyring
exec-once = gnome-keyring

## Hyprsunset (deixa tela amarelada)
exec-once = hyprsunset

## Todoist
exec-once = [workspace 0 silent] com.todoist.Todoist

