## Cursor
env = XCURSOR_THEME,XCursor-Pro-Red
env = XCURSOR_SIZE,32
env = HYPRCURSOR_THEME,XCursor-Pro-Red
env = HYPRCURSOR_SIZE,32

## Force all apps to use Wayland (by: Omarchy)
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

## Allow better support for screen sharing (Google Meet, Discord, etc) (by: Omarchy)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

## Display scaling
xwayland {
  force_zero_scaling = true
}
env = GDK_SCALE,1.25
env = QT_SCALE_FACTOR,1.25

## Use XCompose file (by: Omarchy)
env = XCOMPOSEFILE,~/.XCompose

## SSH agent
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket

## Fcitx (layout teclado)
env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
