## Setup 2 monitores

# monitor= DP-2, 1920x1080@60, 0x0, 1
# monitor= HDMI-A-3, 2560x1080, 1920x-540, 1, transform, 3
#
# workspace = 9, monitor:HDMI-A-3, default:true
#
# env = XCURSOR_THEME,XCursor-Pro-Red
# env = XCURSOR_SIZE,24
# env = HYPRCURSOR_THEME,XCursor-Pro-Red
# env = HYPRCURSOR_SIZE,24

## Setup moniitor 4k
# monitor= HDMI-A-3, 2560x1440@60, auto, 1
monitor= HDMI-A-3, 3840x2160@60, auto, 1.25

env = XCURSOR_THEME,XCursor-Pro-Red
env = XCURSOR_SIZE,32
env = HYPRCURSOR_THEME,XCursor-Pro-Red
env = HYPRCURSOR_SIZE,32
env = GDK_SCALE,1.25
env = ELECTRON_OZONE_PLATFORM_HINT=wayland

xwayland {
  force_zero_scaling = true
}
