## Windows and Workspaces
windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = float on, match:class .*
windowrule = size 1240 720, match:class .*
windowrule = center on, match:class .*
windowrule = persistent_size on, match:class .*

## Tiles
# kitty
windowrule = tile on, match:class ^(kitty)$
# zen browser
windowrule = tile on, match:class ^(app.zen_browser.zen)$
# brave browser
windowrule = tile on, match:class ^(brave-browser)$
# google chrome
windowrule = tile on, match:class ^(google-chrome)$
# vs code
windowrule = tile on, match:class ^(code)$
# beekeeper studio
windowrule = tile on, match:class ^(beekeeper-studio)$
# slack
windowrule = tile on, match:class ^(com.slack.Slack)$

## Floats
# wiremix
windowrule = float on, match:class kitty, match:title wiremix
# blueberry
windowrule = float on, match:class blueberry.py, match:title Bluetooth
windowrule = size 800 600, match:class blueberry.py, match:title Bluetooth
windowrule = center on, match:class blueberry.py, match:title Bluetooth

## Pinneds
# zen browser picture n picture
windowrule = float on,  match:title ^(Picture-in-Picture)$
windowrule = pin on,  match:title ^(Picture-in-Picture)$
windowrule = move 2600 1450,  match:title ^(Picture-in-Picture)$
windowrule = size 400 240,  match:title ^(Picture-in-Picture)$
windowrule = float on,  match:title ^(Picture-in-picture)$
windowrule = pin on,  match:title ^(Picture-in-picture)$
windowrule = move 2600 1450,  match:title ^(Picture-in-picture)$
windowrule = size 400 240,  match:title ^(Picture-in-picture)$

## Fullscreen
# games
# windowrule = fullscreen on, match:class ^(steam_app_).*$

## Gradia
windowrule = float on, match:title Gradia
windowrule = size 2560 1440, match:title Gradia
windowrule = center on, match:title Gradia

## Hyprland share picker
windowrule = size 600 300,  match:class ^(hyprland-share-picker)$

## Google Meet
windowrule = move 1800 20,  match:title ^.*(meet.google.com).*$
windowrule = size 593 60,  match:title ^.*(meet.google.com).*$
windowrule = pin on,  match:title ^.*(meet.google.com).*$



## Games
# Tibia
windowrule = tile on, match:class com.tibia.client, match:title Tibia
windowrule = size 2560 1440, match:class com.tibia.client, match:title Tibia
windowrule = center on, match:class com.tibia.client, match:title Tibia
## Steam
# windowrule = float on, match:class steam, match:title Steam
# windowrule = tile on, match:class steam, match:title Steam
# windowrule = size 1920 1080, match:class steam, match:title Steam
windowrule = size unset, match:class steam, match:title Steam
windowrule = center on, match:class steam, match:title Steam
windowrule = size unset, match:initial_class steam
windowrule = center unset, match:initial_class steam

## Steam games
windowrule = size unset, match:class ^(steam_app_).*$
windowrule = workspace 5, match:class ^(steam_app_).*$

# Balatro
windowrule = float on, match:title Balatro
windowrule = size 1920 1080, match:title Balatro
windowrule = center on, match:title Balatro
# The Bazaar
windowrule = float on, match:title ^(The Bazaar)$
windowrule = size 1920 1080, match:title ^(The Bazaar)$
windowrule = center on, match:title ^(The Bazaar)$

# Path of Exile
windowrule = tile on, match:title ^(Path of Exile)$
