## Windows and Workspaces
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = float, class:.*
windowrulev2 = persistentsize, class:.*

# Tiles
windowrulev2 = tile, class:^(kitty)$
windowrulev2 = tile, class:^(app.zen_browser.zen)$
windowrulev2 = tile, class:^(google-chrome)$
windowrulev2 = tile, class:^(Code)$
windowrulev2 = tile, class:^(beekeeper-studio)$

# Floats
windowrulev2 = float, class:^(kitty)$, title:^(wiremix)$
#windowrulev2 = center, class:^(kitty)$, title:^(wiremix)$

# Fullscreen
# - games
windowrulev2 = fullscreen, class:^(steam_app_).*$


