# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "btrfs" ];

  # Descriptografia LUKS
  boot.initrd.luks.devices.home-encrypted = {
    device = "/dev/disk/by-uuid/c2e12387-d0ea-4f1c-9daf-9511c669289e";
    allowDiscards = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4d9aeb1b-9c88-49f0-a314-f88c153d4996";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FB75-26D6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" = {
    device = "/dev/mapper/home-encrypted";
    fsType = "btrfs";
    options = [ "subvol=@home" "defaults" "noatime" "compress=zstd" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
